package com.wedriveu.mobile.service.login;

import android.app.Activity;
import android.os.AsyncTask;
import android.util.Log;
import com.rabbitmq.client.ExceptionHandler;
import com.wedriveu.mobile.model.User;
import com.wedriveu.mobile.service.ServiceExceptionHandler;
import com.wedriveu.mobile.service.ServiceOperationCallback;
import com.wedriveu.mobile.service.ServiceResult;
import com.wedriveu.shared.entity.LoginRequest;
import com.wedriveu.shared.entity.LoginResponse;
import com.wedriveu.shared.rabbitmq.communication.RabbitMqCommunicationManager;
import com.wedriveu.shared.rabbitmq.communication.DefaultRabbitMqCommunicationManager;
import com.wedriveu.shared.rabbitmq.communication.config.RabbitMqCommunicationConfig;
import com.wedriveu.shared.rabbitmq.communication.config.RabbitMqQueueConfig;
import com.wedriveu.shared.rabbitmq.communication.strategy.RabbitMqCloseCommunicationStrategy;
import com.wedriveu.shared.rabbitmq.communication.strategy.RabbitMqConsumerStrategy;
import com.wedriveu.shared.util.Constants;

import java.io.IOException;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import static com.wedriveu.mobile.util.Constants.CLOSE_COMMUNICATION_ERROR;
import static com.wedriveu.mobile.util.Constants.NO_RESPONSE_DATA_ERROR;

/**
 * The type Login service.
 *
 * @author Marco Baldassarri
 * @author Nicola Lasagni
 * @since 18 /07/2017
 */
public class LoginServiceImpl implements LoginService {

    private static final String TAG = LoginServiceImpl.class.getSimpleName();
    private static final String LOGIN_ERROR = "Error occurred while performing login operation.";

    private Activity mActivity;
    private RabbitMqCommunicationManager mCommunicationManager;

    /**
     * Instantiates a new {@linkplain LoginService}.
     *
     * @param activity the activity used to perform needed callback actions on the UI thread.
     */
    public LoginServiceImpl(Activity activity) {
        mActivity = activity;
        mCommunicationManager = new DefaultRabbitMqCommunicationManager();
    }

    @Override
    public void login(final String username,
                      final String password,
                      final ServiceOperationCallback<User> callback) {
        new AsyncTask<Void, Void, Void>() {

            @Override
            protected Void doInBackground(Void... voids) {
                ServiceResult<User> result;
                try {
                    ExceptionHandler exceptionHandler = new ServiceExceptionHandler(mActivity, callback);
                    RabbitMqCommunicationConfig config =
                            new RabbitMqCommunicationConfig.Builder()
                                    .host(Constants.RabbitMQ.Broker.HOST)
                                    .password(Constants.RabbitMQ.Broker.PASSWORD)
                                    .exceptionHandler(exceptionHandler).build();
                    mCommunicationManager.setUpCommunication(config);
                    String requestId = mCommunicationManager.addAutoGeneratedQueue();
                    LoginRequest request = createRequest(requestId, username, password);
                    sendRequest(request);
                    final BlockingQueue<LoginResponse> response = new ArrayBlockingQueue<>(1);
                    LoginResponse responseBody = subscribeForResponse(requestId, response);
                    result = createServiceResult(responseBody, request);
                    if (result.succeeded()) {
                        String userQueue = String.format(Constants.RabbitMQ.Queue.USER, request.getUsername());
                        RabbitMqQueueConfig queueConfig =
                                new RabbitMqQueueConfig.Builder()
                                        .queueName(userQueue)
                                        .durable(true)
                                        .exclusive(false)
                                        .autoDelete(true)
                                        .build();
                        mCommunicationManager.addQueue(queueConfig);
                    }
                    closeCommunication(requestId);
                } catch (IOException | TimeoutException | InterruptedException e) {
                    Log.e(TAG, LOGIN_ERROR, e);
                    result = new ServiceResult<>(null, LOGIN_ERROR);
                }
                handleResponse(result, callback);
                return null;
            }


        }.execute();
    }

    private void closeCommunication(String requestId) {
        try {
            RabbitMqCloseCommunicationStrategy strategy = new LoginCloseCommunicationStrategy(requestId);
            mCommunicationManager.closeCommunication(strategy);
        } catch (IOException | TimeoutException e) {
            Log.e(TAG, CLOSE_COMMUNICATION_ERROR, e);
        }
    }

    private LoginRequest createRequest(String requestId, String username, String password) {
        LoginRequest request = new LoginRequest();
        request.setRequestId(requestId);
        request.setUsername(username);
        request.setPassword(password);
        return request;
    }

    private void sendRequest(LoginRequest request) throws IOException {
        mCommunicationManager.publishMessage(Constants.RabbitMQ.Exchanges.USER,
                Constants.RabbitMQ.RoutingKey.LOGIN,
                request);
    }

    private LoginResponse subscribeForResponse(String requestId, BlockingQueue<LoginResponse> responseBlockingQueue)
            throws IOException, InterruptedException {
        RabbitMqConsumerStrategy<LoginResponse> strategy = new LoginConsumerStrategy(requestId, responseBlockingQueue);
        mCommunicationManager.registerConsumer(strategy, LoginResponse.class);
        return responseBlockingQueue.poll(com.wedriveu.mobile.util.Constants.SERVICE_OPERATION_TIMEOUT,
                TimeUnit.MILLISECONDS);
    }

    private ServiceResult<User> createServiceResult(LoginResponse response,
                                                    LoginRequest request) throws IOException {
        User user = null;
        String error = "";
        if (response == null) {
            error = NO_RESPONSE_DATA_ERROR;
        } else if (response.isSuccess()) {
            user = new User(request.getUsername(), request.getPassword());
        } else {
            error = response.getErrorMessage();
        }
        return new ServiceResult<>(user, error);
    }

    private void handleResponse(final ServiceResult<User> result,
                                final ServiceOperationCallback<User> callback) {
        mActivity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                callback.onServiceOperationFinished(result);
            }
        });
    }

}
